SELECT * FROM employees;
SELECT last_name, salary FROM employees;
SELECT last_name, salary*nvl(commission_pct,0) +salary FROM employees;
SELECT last_name, salary/20 FROM employees;
SELECT last_name, salary/20 dniowka FROM employees;
SELECT last_name || ' ' || department_id FROM employees;
SELECT DISTINCT first_name FROM employees;
SELECT last_name, first_name, department_id dep_id FROM employees ORDER BY 1,dep_id, salary;
SELECT last_name, first_name, department_id dep_id FROM employees ORDER BY 1,dep_id, salary DESC;
SELECT * FROM employees WHERE department_id=40 OR department_id=50 OR department_id =80;
SELECT * FROM employees WHERE department_id IN (40,50,80);
SELECT * FROM employees WHERE commission_pct IS NULL;
SELECT * FROM employees WHERE commission_pct IS NOT NULL;
SELECT * FROM employees WHERE job_id LIKE '%CLERK';
SELECT * FROM employees WHERE upper(job_id) LIKE '%CLERK';
SELECT  department_id , count(employee_id) FROM employees GROUP BY department_id;
SELECT  department_id , job_id , count(employee_id) count FROM employees GROUP BY department_id, job_id;
SELECT  MIN(salary),MAX(salary),avg(salary) FROM employees GROUP BY job_id;
SELECT first_name FROM employees WHERE department_id = 30;
SELECT first_name FROM employees WHERE department_id = 60;
SELECT first_name FROM employees WHERE department_id = 30 INTERSECT SELECT first_name FROM employees WHERE department_id = 60;
SELECT * FROM employees CROSS JOIN departments;
SELECT * FROM employees e JOIN departments d ON (e.department_id=d.department_id);
SELECT * FROM employees e JOIN departments USING (department_id);
SELECT * FROM employees NATURAL JOIN departments;
SELECT MIN(salary) FROM employees;
SELECT last_name FROM employees WHERE salary=(SELECT MIN(salary) FROM employees);
SELECT last_name, department_id, hire_date FROM employees WHERE (department_id, hire_date) IN (SELECT department_id, MIN(hire_date) FROM employees GROUP BY department_id);
